version: '3'

# expected to define
#
#  STORE_INDEXER_IMAGE_NAME: '{{.STORE_INDEXER_IMAGE_NAME }}'
#  STORE_INDEXER_IMAGE_TAG: '{{.STORE_INDEXER_IMAGE_TAG }}'
#  STORE_INDEXER_PLATFORM: '{{.STORE_INDEXER_PLATFORM }}'

dotenv: [".env.indexers"]

includes:
  bootstrap:
    taskfile: ./taskfiles/Taskfile_bootstrap.yml
  docker:
    taskfile: ./taskfiles/Taskfile_docker.yml

  full:
    taskfile: ./taskfiles/Taskfile_indexers.yml
    vars:
      DIR: indexers/biomesaw-redstone-full

  recent:
    taskfile: ./taskfiles/Taskfile_indexers.yml
    vars:
      DIR: indexers/biomesaw-redstone-recent

tasks:

  build:
    desc: Build the store-indexer image
    cmds:
      - task: docker:build:store-indexer
